name: Hello world
on:
  workflow_dispatch:
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: |
          echo "Hello from Github Actions !"
          echo "next line of code"
          pwd
          echo "Today's date is:"
          date
